// Header lockup: the square, divider, FULLSET wordmark and tagline come from
// logo-header-base.png (generated by scripts/brand-assets.mjs from the
// original artwork, background made transparent and the square's inside
// cleared), with the FS mark from brand/fullset-lockup.svg placed over the
// square as a real SVG so it stays sharp at any size. Positions are
// percentages of the 1320×422 base image, so the mark tracks the square at
// whatever height the image is rendered.
export default function BrandLogo({ className }: { className?: string }) {
  return (
    <span className="relative inline-block align-middle">
      <img src="/brand/logo-header-base.png" alt="Full Set — Your team. The full set." className={className} />
      <img
        src="/brand/fullset-lockup.svg"
        alt=""
        aria-hidden="true"
        className="absolute pointer-events-none"
        style={{ left: "7.69%", top: "27.96%", width: "16.29%" }}
      />
    </span>
  );
}
